name: example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  anecdotes:
    path: ../../anecdotes/
  anecdotes_catalog:
    path: ../
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3
  maestro_just_audio:
    path: ../../maestro_just_audio/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/audio/
