name: example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  anecdotes:
    git:
      url: https://github.com/Papi-Eruh/anecdotes.git
  anecdotes_catalog:
    path: ../
  flutter:
    sdk: flutter
  maestro_just_audio:
    git: 
      url: https://github.com/Papi-Eruh/maestro_just_audio.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/audio/
