name: anecdotes_catalog
description: A catalog of models/widgets to populate anecdotes widgets. 
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  anecdotes:
    git:
      url: https://github.com/Papi-Eruh/anecdotes.git
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.1
  rive: ^0.14.0
  xml: ^6.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  assets:
    - assets/flags/
    - assets/images/
