name: anecdotes_catalog
description: A catalog of models/widgets to populate anecdotes widgets. 
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  anecdotes:
    path: ../anecdotes
  heart:
    path: ../heart
  widia:
    path: ../widia
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.1
  maestro:
    path: ../maestro
  rive: ^0.14.0-dev.7
  xml: ^6.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  assets:
    - assets/flags/
    - assets/images/
